### ISSUE TITLE
Can't Figure out how to 'load' theme

### ISSUE THREAD

**Issue by MarlinspikeHall** [Tenyryas/swade-cyber-css#1]
Hello! I am not really familiar with coding (although I have dabbled in it, in an extremely superficial way in the past). I'm not really sure if my issue is simply me not understanding _how_ to 'load' this css theme into my foundry. Do I need to be adding code to something? Or should it be as simple as installing the module, and then selecting it from the configuration settings... 

Thanks!

**Comment by Tenyryas** [comment]
This is an old theme that I haven't updated in a while, but it should still be compatible with the latest version of SWADE if you use the Community Sheet. You can change it by going on your Character Sheet, and select Sheet next to the Tweaks button.

**Comment by MarlinspikeHall** [comment]
Thank you! I'll try that out tonight when I get home from work. I was so close to doing the process you mention last night, but then I veered off and tried something else... 

Your theme looks awesome, and I'd really like to use it for a game I have coming up this weekend if possible!
