### ISSUE TITLE
Latest update is not compatible with Better Roles

### ISSUE THREAD

**Issue by TopshelfTX** [Tenyryas/swade-cyber-css#4]
Hi! I love the Module and was excited to see the latest update come so quickly to add color back to the skill dice. When I installed it I noticed that clicking on the Quick Access tab did not bring up the cast box in the chat menu that works so well with Better Roles 2 for Savage Worlds as it did before. Is there a way the mod can be made compatible with Better roles? Perhaps have the new updates to quick access casting be optional?

I have reverted back to .31 in the meantime and it is working fine again. Thank you for creating this module!

**Comment by Tenyryas** [comment]
I'm not too sure what you're talking about. Do you mean these neat chat cards?
![SWADE_BR2](https://user-images.githubusercontent.com/61804473/172371126-46277e3f-c8a0-4e96-8555-019c87b1fe5d.png)
In which case it works perfectly on my side. This module is only changing CSS, mind you, so it shouldn't interfere with anything else but that. You should check your module list, or your Better Rolls settings (especially the single click action setting), to see if anything else is interfering.

**Comment by TopshelfTX** [comment]
You are absolutely right, I went to the current module today and it works as intended. Thank you for setting me straight, looks like it was another bug or connection issue not related to your awesome module. 

And to make it clear - the module is much appreciated and awesome. When my players first saw it after using the default charater sheet they loved it. Much more in line with our game's look. 

![2022-06-07 (2)](https://user-images.githubusercontent.com/106982984/172396112-a6a1bd49-d1ec-4912-8a3b-dcd49b76457c.png)

**Comment by Tenyryas** [comment]
It's all good. Hope you guys have fun. :)
