### ISSUE TITLE
Style in Compendiums

### ISSUE THREAD

**Issue by aeciobf** [Tenyryas/swade-cyber-css#5]
Great module!
How to set the style in Compendiums?

**Comment by Tenyryas** [comment]
Not sure if that's what you meant, but the newest update should now cover both old style and toc compendiums.

**Comment by aeciobf** [comment]
Hello friend!
Sorry for the confusion.
I wanted to say if it is possible to insert the CSS in the Journal.

**Comment by Tenyryas** [comment]
Ah, yes, that's also something that it seems I need to update. i'll see
